import type { Metadata } from 'next';
import { montserrat } from './fonts';
import './globals.css';
import Provider from '@/features/login/provider/auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
